theme: jekyll-theme-minimal
title: Sunwook Hwang
description: <p><b>Ph.D., Postdoc Researcher </b><br>Dept. of ECE, SNU, Seoul, Korea</p>
#logo: https://drive.google.com/uc?id=18gWVNOwDDr0tqDWHURX-45aBHEsQSbj0
# logo: https://drive.google.com/uc?export=view&id=18gWVNOwDDr0tqDWHURX-45aBHEsQSbj0/preview
logo: /assets/img/sunwook.jpeg
show_downloads: false
google_analytics:
